name: End-to-end tests with Container 🧪

on: push

jobs:
    compile:
        name: Compile site assets
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v3
          - name: Run the build process with Docker
            uses: addnab/docker-run-action@v3
            with:
                image: docker://wlsf82/gitlab-ce:latest
                options: -v ${{ github.workspace }}:/var/www
                run: |
                    composer install
                    npm install
                    npm run production