name: End-to-end tests with Container 🧪

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://wlsf82/gitlab-ce

    steps:
      - name: Run Commands
        run: |
             composer install
             npm install
             npm run production

      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm start